# Generated by Django 4.0.3 on 2022-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('pubdate', models.DateTimeField(default=0)),
                ('link', models.FileField(default=0, upload_to='')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
