# Generated by Django 4.0.3 on 2022-06-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.FileField(default=0, upload_to='upload'),
        ),
    ]
